import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
});

async function callGemini({ model, messages }) {
    const contents = messages.map((message) => ({
        role: message.role === "assistant" ? "model" : "user",
        parts: [{ text: message.content }],
    }));

    const response = await ai.models.generateContent({
        model,
        contents,
    });

    return {
        text: response.text,
        inputTokens: response.usageMetadata?.promptTokenCount ?? 0,
        outputTokens: response.usageMetadata?.candidatesTokenCount ?? 0,
        totalTokens: response.usageMetadata?.totalTokenCount ?? 0,
    };
}

function isRetryableError(error) {
    const message = error?.message || "";

    return (
        message.includes("503") ||
        message.includes("UNAVAILABLE") ||
        message.includes("429") ||
        message.includes("RESOURCE_EXHAUSTED") ||
        message.includes("timeout")
    );
}

export async function generateWithGemini({ model, messages }) {
    const maxAttempts = 2;

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        try {
            return await callGemini({
                model,
                messages,
            });
        } catch (error) {
            console.error(
                `Gemini attempt ${attempt} failed:`,
                error.message
            );

            if (attempt === maxAttempts || !isRetryableError(error)) {
                break;
            }

            await new Promise((resolve) => setTimeout(resolve, 1000));
        }
    }

    return {
        text: "Primary LLM provider is temporarily unavailable. This response was generated by the gateway fallback.",
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
        provider: "mock",
        status: "fallback",
    };
}